# Generated by Django 4.0.4 on 2022-05-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
    ]
